curious_file_upload_delete_temporary:
    path: /upload/session/files/delete
    defaults: { _controller: CuriousInc\FileUploadFormTypeBundle\Controller\FileController::deleteSessionFileAction }

curious_file_upload_delete_persisted:
    path: /upload/persisted/files/delete
    defaults: { _controller: CuriousInc\FileUploadFormTypeBundle\Controller\FileController::deletePersistedFileAction }
