services:
    curious_inc_file_upload_form_type.dropzone_type:
        class:  CuriousInc\FileUploadFormTypeBundle\Form\Type\DropzoneType
        arguments:
            - "@oneup_uploader.templating.uploader_helper"
            - "@oneup_uploader.orphanage_manager"
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: form.type, alias: dropzone }
