services:
    curious_file_upload.dropzone_type:
        class:  CuriousInc\FileUploadFormTypeBundle\Form\Type\DropzoneType
        arguments:
            - '@oneup_uploader.templating.uploader_helper'
            - '@oneup_uploader.orphanage_manager'
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: form.type, alias: dropzone }

    curious_file_upload.file_namer:
        class: CuriousInc\FileUploadFormTypeBundle\Service\FileNamer

    curious_file_upload.twig.uploader_extension:
        class: CuriousInc\FileUploadFormTypeBundle\Twig\Extension\FileUploaderExtension
        arguments:
            - '@oneup_uploader.orphanage_manager'
            - '@session'
            - '%oneup_uploader.orphanage%'
        tags:
            - { name: twig.extension }
