services:
  curious_file_upload.dropzone_type:
    class: CuriousInc\FileUploadFormTypeBundle\Form\Type\DropzoneType
    arguments:
      - '@oneup_uploader.templating.uploader_helper'
      - '@oneup_uploader.orphanage_manager'
      - '@doctrine.orm.entity_manager'
    tags:
        - { name: form.type, alias: dropzone }

  curious_file_upload.twig.uploader_extension:
    class: CuriousInc\FileUploadFormTypeBundle\Twig\Extension\UploaderExtension
    arguments:
      - '@service_container'
      - '@oneup_uploader.orphanage_manager'
      - '@session'
      - '%oneup_uploader.orphanage%'
    tags:
        - { name: twig.extension }

  curious_file_upload.file_namer:
    class: CuriousInc\FileUploadFormTypeBundle\Namer\FileNamer

  curious_file_upload.cardinality_detector:
    class: CuriousInc\FileUploadFormTypeBundle\Detector\CardinalityDetector

